font_family JetBrains Mono
font_size 8
background #000000
foreground #e0e0e0
cursor #ffffff
cursor_text_color #000000
selection_background #555555
selection_foreground #ffffff
color0  #000000
color1  #1a1a1a
color2  #262626
color3  #333333
color4  #404040
color5  #4d4d4d
color6  #666666
color7  #808080
color8  #999999
color9  #b3b3b3
color10 #cccccc
color11 #d9d9d9
color12 #e6e6e6
color13 #f2f2f2
color14 #f7f7f7
color15 #ffffff
window_padding_width 10
confirm_os_window_close 0
background_opacity 0.3
dynamic_background_opacity yes
allow_remote_control yes
